### ISSUE TITLE
Test validator set change

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/posdao-test-setup#20]
1. Launch a test network with some nodes that are not initial validators.
2. [Mint](https://github.com/poanetwork/posdao-test-setup/blob/0cd34e0ffc8801a9495ef666b4abfcb2dfd8bc52/contracts/ERC677BridgeTokenRewardableMock.sol#L416) a sufficient amount of staking tokens to non-validator addresses.
3. Call [`stake`](https://github.com/poanetwork/posdao-test-setup/blob/116cb67228b149fa031cd39ec573a863173171d9/contracts/ERC677BridgeTokenRewardableMock.sol#L611) from non-validator nodes with their addresses.
4. Check that each node that put a stake is selected as validator in a subsequent staking epoch.

**Comment by DemiMarie** [comment]
Depends on https://github.com/poanetwork/posdao-contracts/pull/31

**Comment by vkomenda** [comment]
Fixed by #24.
