### ISSUE TITLE
Rewrite the tests using chai or mocha, don't use Truffle's `contract`

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/posdao-test-setup#21]
[`contract`](https://truffleframework.com/docs/truffle/testing/writing-tests-in-javascript#use-contract-instead-of-describe-) calls the migration contract every time and spends one block duration on that. If we remove all occurrences of `contract`, we can save a lot of time.

Also, `assert.equal` is not equivalent to `chai`'s `.should.be.equal` because only the latter succeeds in getting argument values of account balances, possibly because those are bignums and `assert` cannot evaluate them.

**Comment by vkomenda** [comment]
This looks trivial as long as we don't use the `accounts` argument of the Truffle's `contract`.

**Comment by varasev** [comment]
I'd propose not to use truffle for `posdao-test-setup` at all and use `web3+chai` instead. With `web3` you can do the same things (deploy contracts, write tests) and do all those things more flexible.
