### ISSUE TITLE
Remove `addCandidateBalances.js` and use `BlockRewardAuRa.addExtraReceiver` instead

### ISSUE THREAD

**Issue by varasev** [poanetwork/posdao-test-setup#26]
To be more close to production mode, instead of modifying `spec.json` by [`scripts/addCandidateBalances.js`](https://github.com/poanetwork/posdao-test-setup/blob/c01874b53ee01818a8db755768f65e59bf95ac31/scripts/addCandidateBalances.js) we could use the feature of `BlockRewardAuRa` contract which allows us to mint native coins by a bridge.

We could emulate minting native coins by `erc-to-native` bridge using the [`addExtraReceiver`](https://github.com/poanetwork/posdao-contracts/blob/9a2a63bdecaa8b192ac669686bd3d096f2d3d23b/contracts/abstracts/BlockRewardBase.sol#L56) function. In production mode, this function will be called by bridge to mint coins when a user bridges their ERC tokens from the foreign network (e.g., from Ethereum Mainnet). At the moment such a logic is used by the bridge in `xDai` network.

To be able to call `addExtraReceiver`, first we need to call [`setErcToNativeBridgesAllowed`](https://github.com/poanetwork/posdao-contracts/blob/9a2a63bdecaa8b192ac669686bd3d096f2d3d23b/contracts/abstracts/BlockRewardBase.sol#L68) by the owner to set some bridge's address `A` (bridge's emulated address in our test case). Then this address `A` can call the `addExtraReceiver`.

For our test case, the address `A` could be the same as `owner` address.

This way the coins are minted on the next block after the calling of `addExtraReceiver`. It is done by `BlockRewardAuRa.reward` function https://github.com/poanetwork/posdao-contracts/blob/9a2a63bdecaa8b192ac669686bd3d096f2d3d23b/contracts/BlockRewardAuRa.sol#L83 which is called each time a new block is created.

**Comment by DemiMarie** [comment]
Can we have the “bridge” be the owner, for simplicity?

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/posdao-test-setup/pull/55.
