### ISSUE TITLE
Test malice reports.

### ISSUE THREAD

**Issue by afck** [poanetwork/posdao-test-setup#27]
Add a test where other validators call [`reportMalicious`](https://github.com/poanetwork/posdao-contracts/blob/9a2a63bdecaa8b192ac669686bd3d096f2d3d23b/contracts/ValidatorSetAuRa.sol#L81) for one validator, and verify that it gets banned and removed from the validator set.

Also verify that withdrawing both delegators' and their own stakes from a banned pool is impossible.

**Comment by DemiMarie** [comment]
I have tested this manually (using <https://github.com/poanetwork/parity-ethereum/pull/101>), but no automation.

**Comment by DemiMarie** [comment]
Also no testing that withdrawl fails.

**Comment by DemiMarie** [comment]
I can test the withdrawl failure fairly easily.  The removal from the validator set will be harder to test.

**Comment by varasev** [comment]
We have tested that manually. The `reportMalicious` tests will be added through unit testing in `posdao-contracts` repo.
