### ISSUE TITLE
Stress tests scenarios

### ISSUE THREAD

**Issue by varasev** [poanetwork/posdao-test-setup#40]
1) [x] Checking the `BlockReward.setSnapshot` function.

    Create 200 delegators for each of the validators in the validator set. All the delegators must place minimal stake into the pool of the validator.

    When the next validator set is finalized (i.e. when the `ValidatorSet.finalizeChange` is called), the `BlockReward.setSnapshot` function will be called.

    The block on which the `ValidatorSet.finalizeChange` is called should be created without significant delays.

2) [x] Checking the `BlockReward.reward` function (as a continuation of the previous test).

    On the next staking epoch, the inflated tokens will be minted to the delegators by the `BlockRewardAuRa.reward` function every block.

    The blocks should be created without significant delays.

3) [x] Optimize the `BlockRewardBase._mintNativeCoinsByErcToNativeBridge` internal function.

4) [x] The `StakingAuRa.performOrderedWithdrawals` should be replaced by manual claiming ordered tokens.

5) [x] Checking the `ValidatorSetAuRa.newValidatorSet` function.

    Create 1500 candidates. All of them must place minimal stake into their own pools.

    The `ValidatorSetAuRa.newValidatorSet` will automatically be called by the `BlockRewardAuRa.reward` on the last block of the staking epoch. That block should be created without significant delays.

    The `ValidatorSetAuRa.validatorSetApplyBlock` should return `0` on the very first block of the next staking epoch.

    Test the same when the block is not empty (create there a lot of dummy transactions closing in to the gas limit of the block).

**Comment by phahulin** [comment]
It seems to be difficult to test with 1000 and 1980 candidates, because we'll have to get at least 501 and 991 nodes running for the validator set change to be finalized?

**Comment by varasev** [comment]
For 1000 delegators we don't need to have a lot of candidates or validators. Three validators would be enough to test working with 1000 delegators for each of them.

For the test 4, we also don't need to launch the nodes for the candidates because we just need to see what happens when the `ValidatorSetAuRa.newValidatorSet` is called (it is called before the `finalizeChange`), so we will have 3 blocks before the network stops.

These tests can be done once and then their code may be removed from the test sets. I just wanted to see if the validators nodes may handle such a load on the `BlockReward.reward` and `ValidatorSet.finalizeChange` in 5 seconds block.

**Comment by varasev** [comment]
I'm going to try the test case 1 today.

**Comment by varasev** [comment]
All the optimizations outlined by this issue are done in the [`posdao-contracts commits`](https://github.com/poanetwork/posdao-contracts/commits/master) made between `19 March` and `2 April 2019`. Now the contracts support having up to `1500` candidates and up to `100` delegators per pool. I'm going to change the code of stakes snapshotting and reward distribution so that it would support 200 delegators per pool (instead of current 100), so I'm not closing this issue yet.

**Comment by varasev** [comment]
> I'm going to change the code of stakes snapshotting and reward distribution so that it would support 200 delegators per pool (instead of current 100)

This was done in https://github.com/poanetwork/posdao-contracts/commit/907cbd21d0ccb20813130fb18a6d8ccc7423daa9 and https://github.com/poanetwork/posdao-contracts/commit/00cdc225cb6cf4a30f9c174d456a767be4e0e4de.

**Comment by varasev** [comment]
This issue is complete, so I'm closing it. The inherited issue for limitations is opened here: https://github.com/poanetwork/parity-ethereum/issues/119
