### ISSUE TITLE
Provide Reproduction re parity/10085: 

### ISSUE THREAD

**Issue by lazaridiscom** [poanetwork/posdao-test-setup#45]
re https://github.com/paritytech/parity-ethereum/issues/10085

## Solution A (Custom Parity-Client)

Use this repository for reproduction (**this includes a corrupt database**) :

* https://github.com/lazaridiscom/posdao-test-setup

Originally mentioned within:

* https://github.com/paritytech/parity-ethereum/issues/10085#issuecomment-473507979

### Requirements

For further reproductions:

* should have zero configuration (e.g. checkout & run)
* if possible, should produce smaller db
* executable by programmers not familiar with poa/blockchain in general

### Solution Path B

Similar as A above, but using the standard parity-client

unconfirmed, try with this: https://github.com/poanetwork/posdao-test-setup/tree/web3-bug

use a loop like this (modify start-test-setup to NOT delete the database) to attempt to corrupt the database:

```sh
for i in {1..100}
do
  echo $i
  killall -15 parity
  sleep 2
  ./scripts/start-test-setup2 ~/pj/parity/target/release/parity
  sleep 10
done
```
copy the database once corrupted.

### Solution Path C

Use a kovan setup, launched as close to defaults as possible (e.g. no configuration necessary). Starting point:

https://github.com/paritytech/parity-ethereum/issues/10085#issuecomment-496881985
https://forum.poa.network/t/new-kovan-validator-aws-node-deployment/2401

shrink it down to the minimum necessary to trigger the error (ideally just `parity --chain=kovan`)

confirmed, but has some steps to setup. Possibly just use Docker for simplicity.

**Comment by varasev** [comment]
@lazaridiscom 

> Solution Path A

Note that for `posdao-test-setup` we use our Parity fork: https://github.com/poanetwork/parity-ethereum/tree/aura-pos

The `posdao-test-setup` shouldn't be used with the [original Parity](https://github.com/paritytech/parity-ethereum).

**Comment by lazaridiscom** [comment]
@varasev , would it be possible to modify your test-setup in order to be able to use the standard-parity client? Only if this is not too much effort.

**Comment by lazaridiscom** [comment]
@phahulin , although I've already a recreation of the error locally, I would need your different context (it seems that there are multiple bugs involved).

would it be possible for you to provide a repo with your setup (https://github.com/paritytech/parity-ethereum/issues/10085#issuecomment-496881985)? all files, including the systemd related ones should be included.

Alternatively, you could send me a zip ( info @lazaridiscom ).

Independent of the above:

* On what machine (OS, arch, cpu, mem, disk-type) and how much % of the system resources are eaten up by your node?

* what is the size or the db, and how long takes the recreation usually until it hits on the error?

**Comment by varasev** [comment]
> would it be possible to modify your test-setup in order to be able to use the standard-parity client?

Yes, you can use the `web3-bug` branch - it uses original Parity: https://github.com/poanetwork/posdao-test-setup/tree/web3-bug

Also, you can try https://github.com/varasev/test-block-reward/tree/kovan-switching

**Comment by lazaridiscom** [comment]
very nice. You ever hit personally on the error whilst using those 2 setups?

**Comment by varasev** [comment]
Yes, I've seen the error using the `posdao-test-setup` (as I mentioned [here](https://github.com/paritytech/parity-ethereum/issues/10085#issuecomment-473507979)), but I believe the second one also can be helpful to catch it.

**Comment by lazaridiscom** [comment]
Yes, I saw it and I reproduced myself via the `posdao-test-setup`. I meant the other two:

* https://github.com/poanetwork/posdao-test-setup/tree/web3-bug
* https://github.com/varasev/test-block-reward/tree/kovan-switching

did you hit the error here?

**Comment by varasev** [comment]
As for these branches - I didn't try them for https://github.com/paritytech/parity-ethereum/issues/10085 issue, but you asked the `posdao-test-setup` which would work with the original Parity - the first one is it.

**Comment by phahulin** [comment]
@lazaridiscom if you know about ansible and have a spare Ubuntu 16.04 VM, you can try to spin up a kovan "validator" node using our ansible playbooks
https://forum.poa.network/t/new-kovan-validator-aws-node-deployment/2401
(use some random validator key - your node won't mine blocks but should work otherwise identical to our setup)

**Comment by lazaridiscom** [comment]
closing this for now, as the one reproduction is enouth. Can be reopened if more repros become necessary
