### ISSUE TITLE
Errors after npm run all

### ISSUE THREAD

**Issue by pashagonchar** [poanetwork/posdao-test-setup#63]
Node Package Manager v. 6.9.0
---------
In directory posdao-test-setup I run command npm run all
---------
npm ERR! path /Users/pavelgoncarenko/posdao-test-setup/posdao-contracts/node_modules/solidity-coverage/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /Users/pavelgoncarenko/posdao-test-setup/posdao-contracts/node_modules/solidity-coverage/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /Users/pavelgoncarenko/posdao-test-setup/posdao-contracts/node_modules/solidity-coverage/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pavelgoncarenko/.npm/_logs/2019-09-16T14_58_49_266Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posdao-test-setup@0.0.1 make-spec: `. ./scripts/network-spec && cd ./posdao-contracts && npm i && node ./scripts/make_spec.js && node ../scripts/addCandidateBalances.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posdao-test-setup@0.0.1 make-spec script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pavelgoncarenko/.npm/_logs/2019-09-16T14_58_49_363Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posdao-test-setup@0.0.1 all: `npm i && npm run get-all-submodules && npm run cleanup && npm run compile-posdao-contracts && npm run make-spec && npm run start-test-setup && npm run test && npm run stop-test-setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posdao-test-setup@0.0.1 all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pavelgoncarenko/.npm/_logs/2019-09-16T14_58_49_431Z-debug.log

-------

![image](https://user-images.githubusercontent.com/16716926/64973238-54810d00-d8b3-11e9-9685-220132c2b062.png)

**Comment by phahulin** [comment]
The error appears to be caused by `posdao-contracts` using forked version of `websocket` package via `solidity-coverage`. Dependency tree for `websocket` looks like this:
```
posdao-contracts@0.1.0 posdao-test-setup/posdao-contracts
├─┬ solidity-coverage@0.6.4
│ └─┬ web3@1.0.0-beta.50
│   └─┬ web3-providers@1.0.0-beta.50
│     └── websocket@1.0.26  (git://github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2) <--- Here is the problem
└─┬ web3@1.0.0-beta.52
  └─┬ web3-providers@1.0.0-beta.52
    └── websocket@1.0.28 <--- This version is ok
```
This forked version for some reason ships with `.git` folder and npm refuses to install it, producing `EISGIT` error.
The workaround is to remove `.git` folder manually and continue with the installation
```
# in posdao-test-setup folder
rm -rf node_modules
rm -rf posdao-contracts
npm run all
# wait for it to crash
rm -r posdao-contracts/node_modules/solidity-coverage/node_modules/websocket/.git
# and re-run again to continue
npm run all
# should finish without errors this time
```
Updated version of web3 which does not depend on this fork of `websocket` is already in the master of `solidity-coverage`, so after it's released the issue should resolve itself.
